# backend/Dockerfile
FROM python:3.11-slim

WORKDIR /app

# Installation des dépendances système pour psycopg2 et pgvector
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copie des requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('BAAI/bge-m3')"

# Le code sera monté via un volume pour le dev, 
# mais on copie quand même pour la prod ou le build initial
COPY . .

# La commande est surchargée par le docker-compose en dev
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]